pipeline:
    stages:
        - stage:
              type: CI
              spec:
                  infrastructure:
                      type: KubernetesDirect
                      spec:
                          connectorRef: account.k8s
                          namespace: vfunction
                  execution:
                      steps:
                          - step:
                                type: BuildAndPushDockerRegistry
                                spec:
                                    connectorRef: dockerhub
                                    repo: labs
                                    tags:
                                        - latest
                                    optimize: true
                                name: build and push
                                identifier: build_and_push
                  cloneCodebase: true
              name: stage1
              identifier: stage1
              variables: []
    properties:
        ci:
            codebase:
                repoName: labs
                connectorRef: account.GitHub
                build: <+input>
    projectIdentifier: labs
    orgIdentifier: vFunction
    name: Pipeline1
    identifier: Pipeline1
