pipeline:
    name: Pipeline1
    identifier: Pipeline1
    projectIdentifier: labs
    orgIdentifier: vFunction
    tags: {}
    properties:
        ci:
            codebase:
                connectorRef: account.GitHub
                repoName: labs
                build: <+input>
    stages:
        - stage:
              name: stage1
              identifier: stage1
              description: ""
              type: CI
              spec:
                  cloneCodebase: true
                  infrastructure:
                      type: KubernetesDirect
                      spec:
                          connectorRef: account.k8s
                          namespace: vfunction
                  execution:
                      steps:
                          - step:
                                type: BuildAndPushDockerRegistry
                                name: build and push
                                identifier: build_and_push
                                spec:
                                    connectorRef: account.dockerhub
                                    repo: rymonteiro/labs
                                    tags:
                                        - latest
                                    optimize: true
                                failureStrategies: []
              variables: []
